[project]
name = "diary"
version = "1.0.0"
description = "Simple utility to create and open weekly diary entries"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dateparser>=1.2.2",
    "jinja2>=3.1.6",
    "python-dotenv>=1.1.1",
]
